### ISSUE TITLE
dsadmin.get_methods -- formatting of 'aggregate' results

### ISSUE THREAD

**Issue by andrewjamesturner0** [datashield/opaladmin#1]
When I run `dsadmin.get_methods(opals, 'assign')` the table output displays correctly in the console. However, when I run this with the `aggregate` argument, the table is chopped and split in the console.

**Is there any way to make the output fit the console width and appear neater?**

**Comment by ymarcon** [comment]
No, it's the way R displays a data.frame/matrix.
